# Generated by Django 6.0.4 on 2026-05-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_remove_userprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedusage',
            name='quantity_used',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kilograms used (kg)'),
        ),
    ]
