# Generated by Django 6.0.2 on 2026-04-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(choices=[('chicken', 'Chicken'), ('duck', 'Duck'), ('goose', 'Goose'), ('turkey', 'Turkey'), ('quail', 'Quail'), ('pigs', 'Pigs'), ('goat', 'Goat'), ('fish', 'Fish')], max_length=20),
        ),
    ]
