# Generated by Django 6.0.2 on 2026-04-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
