# Generated by Django 6.0.2 on 2026-04-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_rename_position_employee_name_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='unit',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
