# Generated by Django 6.0.2 on 2026-04-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_notification_soldegg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('feeding', 'Feeding'), ('cleaning', 'Cleaning'), ('egg_collection', 'Egg Collection'), ('health_check', 'Health Check'), ('mortality', 'Mortality')], max_length=20),
        ),
    ]
